version: '3.8'

services:
    postgres:
        image: postgres
        hostname: postgres
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - myLocalNetwork


volumes:
    pg-data: {}         # определение тома pg-data
    
networks:
    myLocalNetwork:     # создана извне: docker network create --driver=bridge myLocalNetwork
        external: true